server:
  port: 9000

# eureka ????
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system
          predicates:
            - args:
                - /system/**
              name: Path
          uri: lb://system
        - id: file
          predicates:
            - args:
                - /file/**
              name: Path
          uri: lb://file
