server:
  port: 9001
  servlet:
    context-path: /system
spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://localhost:3306/video?characterEncoding=UTF8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: video
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
